version: '3'

services:
  script:
    build: ./scripts_node
    volumes:
      - ./scripts_node:/script
    depends_on:
      - db
    entrypoint: /script/entry.sh
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: go-cute
      MYSQL_ROOT_PASSWORD: experiment_pwd
