version: '3'
services:
  script:
    build: ./script
    command: /bin/bash -c 'sleep 5s' && python3 db_experiment.py
    depends_on:
        - db
  db:
    image: mysql
    environment:
          MYSQL_DATABASE: experiment
          MYSQL_ROOT_PASSWORD: experiment
